name: update ics

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update etudiants
        run: wget --timeout=3600 http://vtiutb.univ-artois.fr/icsetudiant/icsetudiant.php || true

      - name: Update groupes
        run: wget --timeout=3600 http://vtiutb.univ-artois.fr/icsetudiant/icsgroupe.php || true
      
      - name: Download ics
        run: bash ./data/sync || true

      - name: Archive ics files
        uses: actions/upload-artifact@v2
        with:
          name: ics
          path: |
            calendars
            !calendars/**/*.txt
